services:
  # Next.js Frontend Application
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    volumes:
      - ./app/prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Python AI Agent
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      - HEALTH_PORT=4001
    restart: unless-stopped
      
